Fix multipart email structure
awdeorio/mailmerge pull request #115
Opened 2021-03-06 22:24 UTC by seshrs

## Context

As discussed in https://stackoverflow.com/a/3984262/5868796, multipart emails should have mime-type `multipart/mixed`. The markdown transformation must embed the text/html message payloads in a `multipart/alternative` payload. Hence, the final payload-structure of an email with attachments transformed by markdown would be:

- `multipart/mixed`
  - `multipart/alternative`
    - `text/plain`
    - `text/html`
  - `attachment 1`
  - `attachment 2`
  - ...

This PR fixes the email structure of multipart messages with attachments and/or contain transformed Markdown. This commit also updates the unit tests to check for the above structure.

## Validation

I sent an email with Markdown and an attachment, and viewed the email on Gmail and on the native MacOS Mail client. The email showed correctly in both cases:

**Gmail:**
<img src="https://user-images.githubusercontent.com/12139762/110222482-7ce23a00-7ea0-11eb-92e2-707cabcfa841.png" width="300">

**MacOS Mail client:**
<img src="https://user-images.githubusercontent.com/12139762/110222470-62a85c00-7ea0-11eb-872c-431bfdbd5d11.png" width="300">

2021-03-09 20:04 UTC, awdeorio requested changes
This looks great!  Thanks @seshrs !  One minor documentation request.

2021-03-10 03:22 UTC, seshrs commented on mailmerge/template_message.py
> +        multipart_message = email.mime.multipart.MIMEMultipart('mixed')
I've added some context to some of the docstrings in 1ab3068bd6eb6711f112ebd3d34bb9850d5997dc. Feel free to update/wordsmith the comments as you see fit :)

2021-03-10 13:06 UTC, awdeorio commented on mailmerge/template_message.py
> +        multipart_message = email.mime.multipart.MIMEMultipart('mixed')
This is super helpful, thank you!

2021-03-10 13:07 UTC, awdeorio approved these changes
LGTM!  I just gotta figure out how to merge the latest develop into somebody else's fork!

2021-03-10 13:19 UTC, seshrs commented
> LGTM! I just gotta figure out how to merge the latest develop into somebody else's fork!

When I cloned this repo, I set the `origin` remote to be my fork, and created an `upstream` remote pointing to this repo. I think you can do something similar to push changes to my branch that reference commits in this repo’s develop. 

I can add a merge commit a bit later today too, if that helps.

2021-03-10 15:04 UTC, awdeorio commented
Double-check my changes on that conflict resolution, then I'll merge!

2021-03-10 17:18 UTC, merged