Continue on errror
awdeorio/mailmerge pull request #118
Opened 2021-03-09 14:24 UTC by MrSeccubus

As a user I work with email addresses that I get from an external party (in this case abuse email addreses from ipinfo.io)

Sometimes these email addresses contain errors that cause the smtp server to report them back to me and fail. I would like it if the software automatically continues/resumes with the next record instead of having to do that manually.

Also I would like to have a log file (in csv format) so that I know which email were not sent.

2021-03-14 13:42 UTC, MrSeccubus commented
I see that the code fails to run on Python 2, but should we still deal with Python 2 given that it is an unsupported language?

Also I don't know how to address the codecov problems.

2021-03-14 13:46 UTC, MrSeccubus commented
This pull request should also address issue #96

2021-05-28 08:40 UTC, MrSeccubus commented
@awdeorio the unit test that is failing is for a python version that is out of support. DO you really want me to fix that specific error?
Otherwise is there anything else that is holding up this PR?

2021-05-28 18:13 UTC, awdeorio commented
> @awdeorio the unit test that is failing is for a python version that is out of support. DO you really want me to fix that specific error?
> Otherwise is there anything else that is holding up this PR?

Thanks for your patience.  I know I've been slow on this and #114. I'll take a closer look at this after finishing up #114 and getting it merged.

2021-06-01 18:17 UTC, awdeorio requested changes
Sorry for the slow review.  Thanks for your contributions!  I left some comments.

2021-06-01 18:17 UTC, awdeorio commented on mailmerge/__main__.py
> +from .log import MailmergeLog
I would lean towards using Python's standard library [logging](https://docs.python.org/3/howto/logging.html) mechanism over building a custom logger.

2021-06-01 18:17 UTC, awdeorio commented on mailmerge/__main__.py
> +@click.option(
I think that creating a log by default is reasonable.  Maybe we can just call it `mailmerge.log`?  That would simplify the command line interface.

2021-06-01 18:17 UTC, awdeorio commented on mailmerge/__main__.py
> +            try:
I think this logic can be simplified after merging in the latest upstream develop.  That includes a try-except block in the message send part.

2021-06-01 18:17 UTC, awdeorio commented on tests/test_main_log_and_continue.py
> +# coding=utf-8
More ideas for tests:
- Log file already exists

2021-06-02 12:34 UTC, MrSeccubus commented
Continueing this work in PR #124

2021-06-02 12:34 UTC, closed without merging